#!/usr/bin/env bash
set -e
pair=ethgbp
sources=(
  bitstamp
  coinbase
  gemini
  kraken
)

case $1 in
  bitstamp|coinbase|gemini) {
    setzer x-price "$1" "$pair"
  };;
  kraken) {
    setzer x-price kraken xeth:zgbp
  };;
  *) {
    export SETZER_MIN_MEDIAN=4
    setzer --price-commands "-$1-" $pair "${sources[@]}"
  };;
esac
